
const productos = [ {id: 1, nombre:"Campera Snow", precio: 350, tipo: "bebida",key:11, descripcion: "lorem Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda laudantium dignissimos error, repellat adipisci obcaecati quae fugiat optio maxime accusantium! Placeat nam dolorem dolores",},
                    {id: 2, nombre:"Pantalon Snow", precio: 300, tipo: "bebida",key:12, descripcion: "lorem Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda laudantium dignissimos error, repellat adipisci obcaecati quae fugiat optio maxime accusantium! Placeat nam dolorem dolores",},
                    {id: 3, nombre:"Gafas Snow", precio: 200, tipo: "ortaliza",key:13, descripcion: "lorem Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda laudantium dignissimos error, repellat adipisci obcaecati quae fugiat optio maxime accusantium! Placeat nam dolorem dolores",},
                    {id: 4, nombre:"Guantes", precio: 150, tipo: "ortaliza",key:14, descripcion: "lorem Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda laudantium dignissimos error, repellat adipisci obcaecati quae fugiat optio maxime accusantium! Placeat nam dolorem dolores",},
                    {id: 5, nombre:"Botas Snow", precio: 350, tipo: "commida",key:15, descripcion: "lorem Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda laudantium dignissimos error, repellat adipisci obcaecati quae fugiat optio maxime accusantium! Placeat nam dolorem dolores",},
                    {id: 6, nombre:"Tabla Snow", precio: 400, tipo: "comida",key:16, descripcion: "lorem Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda laudantium dignissimos error, repellat adipisci obcaecati quae fugiat optio maxime accusantium! Placeat nam dolorem dolores",},
                    {id: 7, nombre:"Skiies", precio: 300, tipo: "limpieza",key:17, descripcion: "lorem Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda laudantium dignissimos error, repellat adipisci obcaecati quae fugiat optio maxime accusantium! Placeat nam dolorem dolores",},
                    {id: 8, nombre:"Palos Skii", precio: 250, tipo: "limpieza",key:18, descripcion: "lorem Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda laudantium dignissimos error, repellat adipisci obcaecati quae fugiat optio maxime accusantium! Placeat nam dolorem dolores",}
]

export default productos